# Generated by Django 4.1.3 on 2023-08-06 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=15)),
                ('money_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_period_given', models.PositiveIntegerField(default=30)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('total_amount_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_period', models.PositiveIntegerField(default=30)),
                ('final_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('previous_due_date', models.DateField(blank=True, null=True)),
                ('pending_amount', models.IntegerField(default=0, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
