# Generated by Django 3.2.20 on 2023-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
