# Generated by Django 3.2.20 on 2023-08-16 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
