# Generated by Django 3.2.20 on 2023-09-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230817_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='amount_per_due',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dues',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
