# Generated by Django 3.2.20 on 2023-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230905_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='number_of_dues',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='per_due_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
